<?php
/**
 * Created by PhpStorm.
 * User: andrey
 * Date: 12.11.18
 * Time: 22:32
 */

namespace app\components;


use yii\base\Widget;

class ContactFormWidget extends Widget {
    public function init() {
//        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run() {
        return $this->render('contact-form');
    }

}